name: Manual Ejecution
on:
  workflow_dispatch:    
    inputs:
      tag:        
        description: 'Tag'        
        default: '@Smoke'        
        required: true

jobs:  
  Build:    
    runs-on: ubuntu-latest
    steps:
    - name: Step 1 - Checkout main branch de GitHub
      uses: actions/checkout@v2
      
    - name: Step 2 - Compiling maven dependencies
      run: mvn install -DskipTests
      
  Testing:    
    runs-on: ubuntu-latest
    needs: Build    
    steps:    
    - name: Step 1 - Checkout main branch de GitHub
      uses: actions/checkout@v2
      
    - name: Step 2 - Set up JDK 15.0.2
      uses: actions/setup-java@v1
      with:
        java-version: 15.0.2

    - name: Step 3 - Download and install Google Chrome latest
      run: |
        wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        sudo apt install ./google-chrome-stable_current_amd64.deb

      
    - name: Step 4 - Executing Automated Tests
      run: mvn test -Pheadless -Pchrome -Pstaging2 -Dcucumber.filter.tags="${{ github.event.inputs.tag }}" 
      
    - name: Step 5 - Generate Artifacts
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: Reporte-COR-Login
        path: target/Reports/
