# This is a basic workflow that is manually triggered

name: Manual Ejecution

on:
  workflow_dispatch:    
    inputs:
      tag:        
        description: 'Tag'
        # Default value if no value is explicitly provided
        default: '@Smoke'
        # Input has to be provided for the workflow to run
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  Build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Compiling maven dependencies
      run: mvn install -DskipTests
      
  Testing:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: Build
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Executing Automated Tests
      run: mvn test -Pheadless -Pchrome -Pstaging2 -Dcucumber.filter.tags="@${{ github.event.inputs.tag }}" 
    - name: Generate Artifacts
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: Reporte-COR-Login
        path: target/Reports/
